reys = input('номер рейса: ')
rusavia = input('название авиакомпании (на русском языке): ')
engavia = input('название авиакомпании (на английском языке): ')
ruscity = input('город прилета (на русском языке): ')
engcity = input('город прилета (на английском языке): ')
print('Заканчивается посадка на рейс', reys, rusavia, 'до', ruscity)
print('This is the final boarding call for', engavia, 'flight', reys, 'to', engcity)
